In [1]:
import numpy as np

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

In [3]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [4]:
pom = np.ones((m,1))
pom

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [7]:
X = np.append(pom,X1, axis = 1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [16]:
np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))

array([2750.,  250.])

In [17]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y)
#a
print(regression.coef_[0])
#b
print(regression.intercept_)

250.0
2750.0


In [18]:
import pandas as pd
import plotly.express as px

In [21]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

In [22]:
print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [23]:
X1 = X1.reshape(m,1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [24]:
Y = Y.reshape(-1,1)
print(Y)

[[3000]
 [3250]
 [3500]
 [3750]
 [4000]
 [4250]]


In [27]:
bias = np.ones((m,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [29]:
X = np.append(bias,X1,axis=1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [32]:
eta = 0.01

w = np.random.rand(2,1)
w

array([[0.76316303],
       [0.21543175]])

In [33]:
intercept = []
coef = []

for i in range(3000):
  gradient = (2/m) * X.T.dot(X.dot(w) - Y)
  w = w - eta * gradient
  intercept.append(w[0][0])
  coef.append(w[1][0])

print(w)

[[2749.95601191]
 [ 250.01027471]]


In [38]:
df = pd.DataFrame(data = {'intercept': intercept, 'coef': coef})
df.head(10)

intercept        coef
0   73.232820  268.429996
1  125.478063  450.213267
2  163.953574  573.198445
3  193.050611  656.184833
4  215.756660  711.961891
5  234.104195  749.230484
6  249.475977  773.909944
7  262.812761  790.027276
8  274.754597  800.322109
9  285.736957  806.658247

In [39]:
df.tail(10)

intercept        coef
2990  2749.954540  250.010618
2991  2749.954706  250.010580
2992  2749.954872  250.010541
2993  2749.955036  250.010503
2994  2749.955200  250.010464
2995  2749.955364  250.010426
2996  2749.955527  250.010388
2997  2749.955689  250.010350
2998  2749.955851  250.010312
2999  2749.956012  250.010275

In [40]:
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')

In [41]:
px.line(df, y='coef', width=800, title='Dopasowanie: coef')